apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingress-gw-install
spec:
  profile: empty
  components:
    ingressGateways:
    - name: istio-ingressgateway-1-10
      namespace: istio-ingress
      enabled: true