---
# Currently only vagrant is getting ssh-agent forwards
# Thus working directory and permissions set separately
- name: Create working directories
  ansible.builtin.file: 
    path: /home/solo/{{ repo_name }}
    state: directory
    mode: 0775
    owner: solo
    group: solo
- name: Download the repo content locally
  ansible.builtin.git:
    repo: "git@github.com:solo-io/{{ repo_name }}"
    dest: /home/solo/{{ repo_name }}
    separate_git_dir: /home/vagrant/{{ repo_name }}.git
    version: master
    single_branch: yes
    depth: 1
    force: yes
    accept_hostkey: yes
  # ssh-agent doesn't allow key to pass through remote sudo commands.
  become: no
  environment:
    GIT_TERMINAL_PROMPT: 0

- name: Change vagrant ownership of repo to solo
  ansible.builtin.file: 
    path: /home/solo/{{ repo_name }}
    state: directory
    recurse: yes
    mode: 0775
    owner: solo
    group: solo
  become: yes
